MESSAGE_MAX_SIZE = 1024

# Size in bytes of request params, -1 = unlimited
DEFAULT_CLIENT_ID_SIZE = 16
DEFAULT_CLIENT_VERSION_SIZE = 1
DEFAULT_CLIENT_CODE_SIZE = 2
DEFAULT_CLIENT_PAYLOAD_SIZE_SIZE = 4
DEFAULT_CLIENT_PAYLOAD_SIZE = -1
